import NavbarComponent from "../components/NavbarComponent"
import "./../styles/globals.css"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <NavbarComponent />
        <img alt="Logo From Rick And Morty" src="/slimeheader.png" className="slime" />
        {children}
      </body>
    </html>
  )
}
